using UnityEngine;
using System.Collections;

public enum EventId{

    CANT_CONNECT_SERVER,
    DIS_CONNECT_SERVER,
    
    HOME_MAIL,
    HOME_CAIYUAN,
    HOME_SKILL,
    HOME_MULTI,
    HOME_ADVENTURE,
    HOME_SHOP,
    HOME_EQUIP,
    HOME_RANK,
    HOME_SETTING,
    CANCEL_MATCH,
    MULTI_EMIT_SKILL,
    MULTI_WIN,
    MULTI_LOSE,

    GOTO_COIN,//
    GOTO_DIAMOND,//
    GOTO_HEART,//
    BUY_COIN,
    BUY_DIAMOND,
    BUY_HEART,

    VEGETABLE_EXPLAIN,
    VEGETABLE_UPGRADE,
    VEGETABLE_ACCELERATE,

    SKILL_DETAIL,
    SKILL_UPGRADE,
    SKILL_ACCELERATE,

    PUSHLEVEL_CLICK_ME,

    PUSHLEVEL_CLICK_POINT,
    PUSHLEVEL_NEXT_STEP,
    ADD_RANDOM_PLAYER,
    ADD_FRIEND,
    ADD_TEAM,
    PUSH_EMIT_SKILL,
    PUSH_WIN,
    PUSH_LOSE,

    EQUIP_INTRO,
    EQUIP_WEAR,
    EQUIP_UNWEAR,

    SWITCH_CHARACTER_VIEW,
    BUY_CHARACTER,
    USE_CHARACTER,

    BIND_SINA,
    BIND_TECENT,
    SHARE,

    #region 新手引导
    VERY_BEGINNING,
    NICKNAME_EDIT,
    NICKNAME_FINISH,
    GUIDE_PROGRESS,
    #endregion
}
